version: '3.4'

services:
  postgres:
    image: postgres:10.4
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ticket_checker
      POSTGRES_USER: ticketUser
      POSTGRES_PASSWORD: 123456987asd

  server:
      image: ticket-checker-server:1.0
      container_name: ticket-checker-server
      build:
        context: .
      restart: unless-stopped
      ports:
      - "8080:8080"
      links:
      - postgres
      depends_on:
      - postgres